//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _06.ReadExcelDoc {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings6 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings6 defaultInstance = ((Settings6)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings6())));
        
        public static Settings6 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sasho\Desktop\table.xlsx;Extended Properties='Excel 12.0 Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sasho\Desktop\table.xlsx;Extended Properties='Excel 12.0 Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sash
o\Desktop\table.xlsx;Extended Properties='Excel 12.0 Xml;HDR=Yes")]
        public string conString {
            get {
                return ((string)(this["conString"]));
            }
            set {
                this["conString"] = value;
            }
        }
    }
}
